In [1]:
import numpy as np
import pandas as pd

In [2]:
# 对比赛表match表的数据处理操作
df = pd.read_csv('../data/match.csv')
df.head(2)
# 将赛季字段的/更换为-(请尝试使用多种方法)
df['season'].str.replace('/','-')
df['season'].apply(lambda x:x.replace('/','-'))
df.replace('/','-',regex=True)
# 对主队进球列实现等宽分箱操作，分为5个区间，并实现分箱后值的统计
pd.cut(df['home_team_goal'],bins=5)
pd.cut(df['home_team_goal'],bins=5).value_counts().sort_index()
# 对客队进球列实现等宽分箱操作，分为5个区间，并实现分箱后值的统计
pd.cut(df['away_team_goal'],bins=5)
pd.cut(df['away_team_goal'],bins=5).value_counts().sort_index()
# 统计每条比赛记录已经距现在多少年，并将获得的数据设置为matchyear
pd.to_datetime(df['date'])
today_year = pd.to_datetime('today').year
df.assign(
    matchyear = df['date'].apply(lambda x:today_year-pd.to_datetime(x).year)
)
# df.assign(
#     matchyear = pd.to_datetime(df['date']).apply(lambda x:today_year-pd.to_datetime(x).year)
# )
# 设置比赛日期date为索引
df.date = pd.to_datetime(df.date)
df.set_index('date',inplace=True)
df
# 获得2008-08-17的全部比赛数据
df.loc['2008-08-17']
# 获得2008-08的全部比赛数据
df.loc['2008-08']
# 利用时间索引获得2008-08-17到2008-08-31的全部比赛数据
df.loc['2008-08-17':'2008-08-31']

,league_id,season,stage,match_api_id,date,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal
0,1,2008/2009,24,493017,2009/2/27 0:00,8203,9987,2,1
1,1,2008/2009,25,493025,2009/3/8 0:00,9984,8342,1,3

0        2008-2009
1        2008-2009
2        2008-2009
3        2008-2009
4        2008-2009
           ...
21356    2015-2016
21357    2015-2016
21358    2015-2016
21359    2015-2016
21360    2015-2016
Name: season, Length: 21361, dtype: object

0        2008-2009
1        2008-2009
2        2008-2009
3        2008-2009
4        2008-2009
           ...
21356    2015-2016
21357    2015-2016
21358    2015-2016
21359    2015-2016
21360    2015-2016
Name: season, Length: 21361, dtype: object

,league_id,season,stage,match_api_id,date,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal
0,1,2008-2009,24,493017,2009-2-27 0:00,8203,9987,2,1
1,1,2008-2009,25,493025,2009-3-8 0:00,9984,8342,1,3
2,1,2008-2009,25,493027,2009-3-7 0:00,8635,10000,2,0
3,1,2008-2009,26,493034,2009-3-13 0:00,8203,8635,2,1
4,1,2008-2009,26,493040,2009-3-14 0:00,10000,9999,0,0
...,...,...,...,...,...,...,...,...,...
21356,24558,2015-2016,8,1992089,2015-9-13 0:00,10243,10191,3,3
21357,24558,2015-2016,9,1992091,2015-9-22 0:00,10190,10191,1,0
21358,24558,2015-2016,9,1992092,2015-9-23 0:00,9824,10199,1,2
21359,24558,2015-2016,9,1992093,2015-9-23 0:00,9956,10179,2,0
21360,24558,2015-2016,9,1992095,2015-9-23 0:00,10192,9931,4,3

0        (-0.01, 2.0]
1        (-0.01, 2.0]
2        (-0.01, 2.0]
3        (-0.01, 2.0]
4        (-0.01, 2.0]
             ...
21356      (2.0, 4.0]
21357    (-0.01, 2.0]
21358    (-0.01, 2.0]
21359    (-0.01, 2.0]
21360      (2.0, 4.0]
Name: home_team_goal, Length: 21361, dtype: category
Categories (5, interval[float64, right]): [(-0.01, 2.0] < (2.0, 4.0] < (4.0, 6.0] < (6.0, 8.0] < (8.0, 10.0]]

home_team_goal
(-0.01, 2.0]    16895
(2.0, 4.0]       3903
(4.0, 6.0]        518
(6.0, 8.0]         39
(8.0, 10.0]         6
Name: count, dtype: int64

0        (-0.009, 1.8]
1           (1.8, 3.6]
2        (-0.009, 1.8]
3        (-0.009, 1.8]
4        (-0.009, 1.8]
             ...
21356       (1.8, 3.6]
21357    (-0.009, 1.8]
21358       (1.8, 3.6]
21359    (-0.009, 1.8]
21360       (1.8, 3.6]
Name: away_team_goal, Length: 21361, dtype: category
Categories (5, interval[float64, right]): [(-0.009, 1.8] < (1.8, 3.6] < (3.6, 5.4] < (5.4, 7.2] < (7.2, 9.0]]

away_team_goal
(-0.009, 1.8]    14432
(1.8, 3.6]        6070
(3.6, 5.4]         788
(5.4, 7.2]          65
(7.2, 9.0]           6
Name: count, dtype: int64

0       2009-02-27
1       2009-03-08
2       2009-03-07
3       2009-03-13
4       2009-03-14
           ...
21356   2015-09-13
21357   2015-09-22
21358   2015-09-23
21359   2015-09-23
21360   2015-09-23
Name: date, Length: 21361, dtype: datetime64[ns]

KeyboardInterrupt: