In [3]:
import numpy as np
import pandas as pd

In [4]:
# >加载比赛数据集
df = pd.read_csv('..\data\match.csv')
df.head(3)
# >实现数据基本信息检视
df.describe()
df.info()
# >通过isnull0判断各列是否存在空值
df.isnull().sum()
# >以默认方式删除数据集的缺失值
df.dropna(inplace=True)
df.isnull().sum()
# >显示数据的描述信息
df.info()
# >使用value_counts(检测主队进球和客队进球的异常值
df.home_team_goal.value_counts()
df.away_team_goal.value_counts()
# >过滤异常数据
df = df[(df.home_team_goal>=0) & (df.away_team_goal>=0)]
df.info()
# >判断重复数据(以所有字段均相同为判断重复的标准
df.duplicated().sum()

,league_id,season,stage,match_api_id,date,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal
0,1,2008/2009,24,493017,2009/2/27 0:00,8203,9987,2,1
1,1,2008/2009,25,493025,2009/3/8 0:00,9984,8342,1,3
2,1,2008/2009,25,493027,2009/3/7 0:00,8635,10000,2,0

,league_id,stage,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal
count,21361.000000,21361.000000,2.136100e+04,21361.000000,21361.000000,21361.000000,21361.000000
mean,11226.894855,18.578859,1.251718e+06,9979.096765,10049.537849,1.557465,1.175226
std,7640.636869,10.469957,4.805970e+05,13151.299294,13583.487751,1.303871,1.149807
min,1.000000,1.000000,4.831300e+05,1601.000000,1601.000000,0.000000,0.000000
25%,4769.000000,10.000000,8.401550e+05,8530.000000,8530.000000,1.000000,0.000000
50%,10257.000000,19.000000,1.227832e+06,9747.000000,9747.000000,1.000000,1.000000
75%,19694.000000,27.000000,1.712696e+06,9911.000000,9911.000000,2.000000,2.000000
max,24558.000000,38.000000,2.216671e+06,274581.000000,274581.000000,10.000000,9.000000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21361 entries, 0 to 21360
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   league_id         21361 non-null  int64
 1   season            21361 non-null  object
 2   stage             21361 non-null  int64
 3   match_api_id      21361 non-null  int64
 4   date              21361 non-null  object
 5   home_team_api_id  21361 non-null  int64
 6   away_team_api_id  21361 non-null  int64
 7   home_team_goal    21361 non-null  int64
 8   away_team_goal    21361 non-null  int64
dtypes: int64(7), object(2)
memory usage: 1.5+ MB

league_id           0
season              0
stage               0
match_api_id        0
date                0
home_team_api_id    0
away_team_api_id    0
home_team_goal      0
away_team_goal      0
dtype: int64

league_id           0
season              0
stage               0
match_api_id        0
date                0
home_team_api_id    0
away_team_api_id    0
home_team_goal      0
away_team_goal      0
dtype: int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21361 entries, 0 to 21360
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   league_id         21361 non-null  int64
 1   season            21361 non-null  object
 2   stage             21361 non-null  int64
 3   match_api_id      21361 non-null  int64
 4   date              21361 non-null  object
 5   home_team_api_id  21361 non-null  int64
 6   away_team_api_id  21361 non-null  int64
 7   home_team_goal    21361 non-null  int64
 8   away_team_goal    21361 non-null  int64
dtypes: int64(7), object(2)
memory usage: 1.5+ MB

home_team_goal
1     6867
2     5228
0     4800
3     2730
4     1173
5      381
6      137
7       31
8        8
9        4
10       2
Name: count, dtype: int64

away_team_goal
1    7385
0    7047
2    4270
3    1800
4     609
5     179
6      56
7       9
8       5
9       1
Name: count, dtype: int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21361 entries, 0 to 21360
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   league_id         21361 non-null  int64
 1   season            21361 non-null  object
 2   stage             21361 non-null  int64
 3   match_api_id      21361 non-null  int64
 4   date              21361 non-null  object
 5   home_team_api_id  21361 non-null  int64
 6   away_team_api_id  21361 non-null  int64
 7   home_team_goal    21361 non-null  int64
 8   away_team_goal    21361 non-null  int64
dtypes: int64(7), object(2)
memory usage: 1.5+ MB

0