In [2]:
from unittest.mock import inplace

import pandas as pd
import numpy as np

In [5]:
d = [
    [1,'张三',18,'男','北京海淀'],
    [2,'张二',19,'男','北京朝阳'],
    [3,'张三',20,'男','北京大兴']
]
df1 = pd.DataFrame(data=d, index=[1,2,3], columns=['编号','姓名','年龄','性别','地址'])
print(df1)

dict1 = {
    '学员1':[1,'张三',18,'男','北京海淀'],
    '学员2':[2,'张二',19,'男','北京朝阳'],
    '学员3':[3,'张三',20,'男','北京大兴']
}
df2 = pd.DataFrame(data=dict1, index=['编号','姓名','年龄','性别','地址'])
df2

names = pd.Series(['张毅','张二','张三'],name='姓名')
names.to_frame()

   编号  姓名  年龄 性别    地址
1   1  张三  18  男  北京海淀
2   2  张二  19  男  北京朝阳
3   3  张三  20  男  北京大兴

     学员1   学员2   学员3
编号     1     2     3
姓名    张三    张二    张三
年龄    18    19    20
性别     男     男     男
地址  北京海淀  北京朝阳  北京大兴

   姓名
0  张毅
1  张二
2  张三

In [6]:
df = pd.read_csv('../data/player.csv')
df

       player_api_id          player_name             birthday  height  weight
0             505942   Aaron Appindangoye  1992-02-29 00:00:00  182.88     187
1             155782      Aaron Cresswell  1989-12-15 00:00:00  170.18     146
2             162549          Aaron Doran  1991-05-13 00:00:00  170.18     163
3              30572        Aaron Galindo  1982-05-08 00:00:00  182.88     198
4              23780         Aaron Hughes  1979-11-08 00:00:00  182.88     154
...              ...                  ...                  ...     ...     ...
11055          26357       Zoumana Camara  1979-04-03 00:00:00  182.88     168
11056         111182         Zsolt Laczko  1986-12-18 00:00:00  182.88     176
11057          36491            Zsolt Low  1979-04-29 00:00:00  180.34     154
11058          35506  Zurab Khizanishvili  1981-10-06 00:00:00  185.42     172
11059          39902   Zvjezdan Misimovic  1982-06-05 00:00:00  180.34     176

[11060 rows x 5 columns]

In [4]:
df = pd.read_csv('../data/player.csv')
df = pd.read_csv('../data/player.csv', index_col='player_api_id')
df = pd.read_csv('../data/player.csv', index_col='player_api_id', usecols=['player_api_id', 'player_name', 'birthday'])
df

                       player_name             birthday
player_api_id
505942          Aaron Appindangoye  1992-02-29 00:00:00
155782             Aaron Cresswell  1989-12-15 00:00:00
162549                 Aaron Doran  1991-05-13 00:00:00
30572                Aaron Galindo  1982-05-08 00:00:00
23780                 Aaron Hughes  1979-11-08 00:00:00
...                            ...                  ...
26357               Zoumana Camara  1979-04-03 00:00:00
111182                Zsolt Laczko  1986-12-18 00:00:00
36491                    Zsolt Low  1979-04-29 00:00:00
35506          Zurab Khizanishvili  1981-10-06 00:00:00
39902           Zvjezdan Misimovic  1982-06-05 00:00:00

[11060 rows x 2 columns]

In [5]:
df = pd.read_excel('../data/豆瓣250.xlsx')
df

,排名,中文电影名,外文电影名,电影评分,评分人数,电影简介,电影详情
0,NaN,肖申克的救赎,The Shawshank Redemption,9.7,2410222.0,希望让人自由。,导演: 弗兰克·德拉邦特 Frank Darabont主演: 蒂姆·罗宾斯 Tim Robb...
1,NaN,霸王别姬,缺失,9.6,1793718.0,风华绝代。,导演: 陈凯歌 Kaige Chen主演: 张国荣 Leslie Cheung 张丰毅 ...
2,NaN,阿甘正传,Forrest Gump,9.5,1814052.0,一部美国近现代史。,导演: 罗伯特·泽米吉斯 Robert Zemeckis主演: 汤姆·汉克斯 Tom Han...
3,NaN,这个杀手不太冷,Léon,9.4,1982399.0,怪蜀黍和小萝莉不得不说的故事。,导演: 吕克·贝松 Luc Besson主演: 让·雷诺 Jean Reno 娜塔莉·波...
4,NaN,泰坦尼克号,Titanic,9.4,1775480.0,失去的才是永恒的。,导演: 詹姆斯·卡梅隆 James Cameron主演: 莱昂纳多·迪卡普里奥 Leonar...
...,...,...,...,...,...,...,...
245,NaN,浪潮,Die Welle,8.7,231540.0,世界离独裁只有五天。,导演: 丹尼斯·甘塞尔 Dennis Gansel主演: 尤尔根·沃格尔 Jürgen Vo...
246,NaN,猜火车,Trainspotting,8.5,367598.0,不可猜的青春迷笛。,导演: 丹尼·博伊尔 Danny Boyle主演: 伊万·麦克格雷格 Ewan McGreg...
247,NaN,爱乐之城,La La Land,8.4,692407.0,NaN,导演: 达米恩·查泽雷 Damien Chazelle主演: 瑞恩·高斯林 Ryan Gos...
248,NaN,小萝莉的猴神大叔,Bajrangi Bhaijaan,8.4,418917.0,宝莱坞的萝莉与大叔。,导演: 卡比尔·汗 Kabir Khan主演: 萨尔曼·汗 Salman Khan 哈莎...
249,NaN,背靠背，脸对脸,缺失,9.5,75577.0,NaN,导演: 黄建新 Jianxin Huang 杨亚洲 Yazhou Yang主演: 牛振华...

In [7]:
df = pd.read_csv('../data/player.csv')
# df.to_csv('../data/player2.csv',index= False)
df.to_excel('../data/player2.xlsx',index= False)

In [13]:
df = pd.read_csv('../data/player.csv')
df.dtypes

df = df.astype({'weight':'float64'})
df.dtypes

df.index
df.columns

player_api_id      int64
player_name       object
birthday          object
height           float64
weight             int64
dtype: object

player_api_id      int64
player_name       object
birthday          object
height           float64
weight           float64
dtype: object

RangeIndex(start=0, stop=11060, step=1)

Index(['player_api_id', 'player_name', 'birthday', 'height', 'weight'], dtype='object')

In [16]:
df.index = range(1, 11061)
df.index
df.columns=['球员编号','球员姓名','出生日期','身高','体重']
df.columns
df

df.rename(index = {1: 88888}, inplace= True)
df.rename(columns={'球员编号':'编号'})
df

RangeIndex(start=1, stop=11061, step=1)

Index(['球员编号', '球员姓名', '出生日期', '身高', '体重'], dtype='object')

         球员编号                 球员姓名                 出生日期      身高     体重
1      505942   Aaron Appindangoye  1992-02-29 00:00:00  182.88  187.0
2      155782      Aaron Cresswell  1989-12-15 00:00:00  170.18  146.0
3      162549          Aaron Doran  1991-05-13 00:00:00  170.18  163.0
4       30572        Aaron Galindo  1982-05-08 00:00:00  182.88  198.0
5       23780         Aaron Hughes  1979-11-08 00:00:00  182.88  154.0
...       ...                  ...                  ...     ...    ...
11056   26357       Zoumana Camara  1979-04-03 00:00:00  182.88  168.0
11057  111182         Zsolt Laczko  1986-12-18 00:00:00  182.88  176.0
11058   36491            Zsolt Low  1979-04-29 00:00:00  180.34  154.0
11059   35506  Zurab Khizanishvili  1981-10-06 00:00:00  185.42  172.0
11060   39902   Zvjezdan Misimovic  1982-06-05 00:00:00  180.34  176.0

[11060 rows x 5 columns]

           编号                 球员姓名                 出生日期      身高     体重
88888  505942   Aaron Appindangoye  1992-02-29 00:00:00  182.88  187.0
2      155782      Aaron Cresswell  1989-12-15 00:00:00  170.18  146.0
3      162549          Aaron Doran  1991-05-13 00:00:00  170.18  163.0
4       30572        Aaron Galindo  1982-05-08 00:00:00  182.88  198.0
5       23780         Aaron Hughes  1979-11-08 00:00:00  182.88  154.0
...       ...                  ...                  ...     ...    ...
11056   26357       Zoumana Camara  1979-04-03 00:00:00  182.88  168.0
11057  111182         Zsolt Laczko  1986-12-18 00:00:00  182.88  176.0
11058   36491            Zsolt Low  1979-04-29 00:00:00  180.34  154.0
11059   35506  Zurab Khizanishvili  1981-10-06 00:00:00  185.42  172.0
11060   39902   Zvjezdan Misimovic  1982-06-05 00:00:00  180.34  176.0

[11060 rows x 5 columns]

         球员编号                 球员姓名                 出生日期      身高     体重
88888  505942   Aaron Appindangoye  1992-02-29 00:00:00  182.88  187.0
2      155782      Aaron Cresswell  1989-12-15 00:00:00  170.18  146.0
3      162549          Aaron Doran  1991-05-13 00:00:00  170.18  163.0
4       30572        Aaron Galindo  1982-05-08 00:00:00  182.88  198.0
5       23780         Aaron Hughes  1979-11-08 00:00:00  182.88  154.0
...       ...                  ...                  ...     ...    ...
11056   26357       Zoumana Camara  1979-04-03 00:00:00  182.88  168.0
11057  111182         Zsolt Laczko  1986-12-18 00:00:00  182.88  176.0
11058   36491            Zsolt Low  1979-04-29 00:00:00  180.34  154.0
11059   35506  Zurab Khizanishvili  1981-10-06 00:00:00  185.42  172.0
11060   39902   Zvjezdan Misimovic  1982-06-05 00:00:00  180.34  176.0

[11060 rows x 5 columns]

In [20]:
df = pd.read_csv('../data/player.csv')

df['player_name']
df.player_name
df[['player_name','birthday']]

0         Aaron Appindangoye
1            Aaron Cresswell
2                Aaron Doran
3              Aaron Galindo
4               Aaron Hughes
                ...
11055         Zoumana Camara
11056           Zsolt Laczko
11057              Zsolt Low
11058    Zurab Khizanishvili
11059     Zvjezdan Misimovic
Name: player_name, Length: 11060, dtype: object

0         Aaron Appindangoye
1            Aaron Cresswell
2                Aaron Doran
3              Aaron Galindo
4               Aaron Hughes
                ...
11055         Zoumana Camara
11056           Zsolt Laczko
11057              Zsolt Low
11058    Zurab Khizanishvili
11059     Zvjezdan Misimovic
Name: player_name, Length: 11060, dtype: object

               player_name             birthday
0       Aaron Appindangoye  1992-02-29 00:00:00
1          Aaron Cresswell  1989-12-15 00:00:00
2              Aaron Doran  1991-05-13 00:00:00
3            Aaron Galindo  1982-05-08 00:00:00
4             Aaron Hughes  1979-11-08 00:00:00
...                    ...                  ...
11055       Zoumana Camara  1979-04-03 00:00:00
11056         Zsolt Laczko  1986-12-18 00:00:00
11057            Zsolt Low  1979-04-29 00:00:00
11058  Zurab Khizanishvili  1981-10-06 00:00:00
11059   Zvjezdan Misimovic  1982-06-05 00:00:00

[11060 rows x 2 columns]