In [2]:
import pandas as pd
import numpy as np

In [3]:
# 导入player_attributes表数据
df = pd.read_csv('../data/player_attributes.csv')
# 显示player_attributes表的各项属性
df.dtypes
# 尝试修改某些列的数据类型
df.astype({'player_api_id': 'float64'})
# 尝试修改某些列的列名
df.rename(columns={'player_api_id': 'player_id', 'date': 'data'})
# 调用相关描述函数查看player_attributes表数据信息
df.dtypes
# 统计某一列包含空值的数量
df.isnull().count(True)

id                       int64
player_api_id            int64
date                    object
overall_rating         float64
potential              float64
preferred_foot          object
attacking_work_rate     object
defensive_work_rate     object
crossing               float64
finishing              float64
heading_accuracy       float64
short_passing          float64
volleys                float64
dribbling              float64
curve                  float64
free_kick_accuracy     float64
long_passing           float64
ball_control           float64
acceleration           float64
sprint_speed           float64
agility                float64
reactions              float64
balance                float64
shot_power             float64
jumping                float64
stamina                float64
strength               float64
long_shots             float64
aggression             float64
interceptions          float64
positioning            float64
vision                 float64
penalties              float64
marking                float64
standing_tackle        float64
sliding_tackle         float64
gk_diving              float64
gk_handling            float64
gk_kicking             float64
gk_positioning         float64
gk_reflexes            float64
dtype: object

,id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,0,505942.0,2016/2/18 0:00,67.0,71.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,1,505942.0,2015/11/19 0:00,67.0,71.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,2,505942.0,2015/9/21 0:00,62.0,66.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,3,505942.0,2015/3/20 0:00,61.0,65.0,right,medium,medium,48.0,43.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,4,505942.0,2007/2/22 0:00,61.0,65.0,right,medium,medium,48.0,43.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183973,183973,39902.0,2009/8/30 0:00,83.0,85.0,right,medium,low,84.0,77.0,...,88.0,83.0,22.0,31.0,30.0,9.0,20.0,84.0,20.0,20.0
183974,183974,39902.0,2009/2/22 0:00,78.0,80.0,right,medium,low,74.0,76.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183975,183975,39902.0,2008/8/30 0:00,77.0,80.0,right,medium,low,74.0,71.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183976,183976,39902.0,2007/8/30 0:00,78.0,81.0,right,medium,low,74.0,64.0,...,88.0,53.0,28.0,32.0,30.0,9.0,20.0,73.0,20.0,20.0
183977,183977,39902.0,2007/2/22 0:00,80.0,81.0,right,medium,low,74.0,68.0,...,88.0,53.0,38.0,32.0,30.0,9.0,9.0,78.0,7.0,15.0

,id,player_id,data,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,0,505942,2016/2/18 0:00,67.0,71.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,1,505942,2015/11/19 0:00,67.0,71.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,2,505942,2015/9/21 0:00,62.0,66.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,3,505942,2015/3/20 0:00,61.0,65.0,right,medium,medium,48.0,43.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,4,505942,2007/2/22 0:00,61.0,65.0,right,medium,medium,48.0,43.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183973,183973,39902,2009/8/30 0:00,83.0,85.0,right,medium,low,84.0,77.0,...,88.0,83.0,22.0,31.0,30.0,9.0,20.0,84.0,20.0,20.0
183974,183974,39902,2009/2/22 0:00,78.0,80.0,right,medium,low,74.0,76.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183975,183975,39902,2008/8/30 0:00,77.0,80.0,right,medium,low,74.0,71.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183976,183976,39902,2007/8/30 0:00,78.0,81.0,right,medium,low,74.0,64.0,...,88.0,53.0,28.0,32.0,30.0,9.0,20.0,73.0,20.0,20.0
183977,183977,39902,2007/2/22 0:00,80.0,81.0,right,medium,low,74.0,68.0,...,88.0,53.0,38.0,32.0,30.0,9.0,9.0,78.0,7.0,15.0

id                       int64
player_api_id            int64
date                    object
overall_rating         float64
potential              float64
preferred_foot          object
attacking_work_rate     object
defensive_work_rate     object
crossing               float64
finishing              float64
heading_accuracy       float64
short_passing          float64
volleys                float64
dribbling              float64
curve                  float64
free_kick_accuracy     float64
long_passing           float64
ball_control           float64
acceleration           float64
sprint_speed           float64
agility                float64
reactions              float64
balance                float64
shot_power             float64
jumping                float64
stamina                float64
strength               float64
long_shots             float64
aggression             float64
interceptions          float64
positioning            float64
vision                 float64
penalties              float64
marking                float64
standing_tackle        float64
sliding_tackle         float64
gk_diving              float64
gk_handling            float64
gk_kicking             float64
gk_positioning         float64
gk_reflexes            float64
dtype: object

0         41
1         41
2         41
3         41
4         41
          ..
183973    41
183974    41
183975    41
183976    41
183977    41
Length: 183978, dtype: int64

In [4]:
df = pd.read_csv('../data/team_attributes.csv')
# df.columns
# 显示数据的行列数量
df.columns.size
df.index.size
# 显示team_api_id列
df.team_api_id
# 显示team_api_id和其他列
df[['team_api_id', 'buildUpPlaySpeed']]
# 添加area列的值为Europe
df['area'] = 'Europe'
# 增加buildUpPlayAvg列并赋值为 buildUpPlaySpeed\df.buildUpPlayDribbling\df.buildUpPlayPassing的均值
df['buildUpPlayAvg'] = (df.buildUpPlaySpeed + df.buildUpPlayDribbling + df.buildUpPlayPassing) / 3
df

24

1458

0        9930
1        9930
2        9930
3        8485
4        8485
        ...
1453    10000
1454    10000
1455    10000
1456    10000
1457    10000
Name: team_api_id, Length: 1458, dtype: int64

      team_api_id  buildUpPlaySpeed
0            9930                60
1            9930                52
2            9930                47
3            8485                70
4            8485                47
...           ...               ...
1453        10000                52
1454        10000                54
1455        10000                54
1456        10000                54
1457        10000                54

[1458 rows x 2 columns]

,id,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,buildUpPlayPositioningClass,...,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass,area,buildUpPlayAvg
0,0,9930,2010/2/22 0:00,60,Balanced,NaN,Little,50,Mixed,Organised,...,Organised,50,Medium,55,Press,45,Normal,Cover,Europe,NaN
1,1,9930,2014/9/19 0:00,52,Balanced,48.0,Normal,56,Mixed,Organised,...,Organised,47,Medium,44,Press,54,Normal,Cover,Europe,52.000000
2,2,9930,2015/9/10 0:00,47,Balanced,41.0,Normal,54,Mixed,Organised,...,Organised,47,Medium,44,Press,54,Normal,Cover,Europe,47.333333
3,3,8485,2010/2/22 0:00,70,Fast,NaN,Little,70,Long,Organised,...,Organised,60,Medium,70,Double,70,Wide,Cover,Europe,NaN
4,4,8485,2011/2/22 0:00,47,Balanced,NaN,Little,52,Mixed,Organised,...,Organised,47,Medium,47,Press,52,Normal,Cover,Europe,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1453,1453,10000,2011/2/22 0:00,52,Balanced,NaN,Little,52,Mixed,Organised,...,Organised,46,Medium,48,Press,53,Normal,Cover,Europe,NaN
1454,1454,10000,2012/2/22 0:00,54,Balanced,NaN,Little,51,Mixed,Organised,...,Organised,44,Medium,55,Press,53,Normal,Cover,Europe,NaN
1455,1455,10000,2013/9/20 0:00,54,Balanced,NaN,Little,51,Mixed,Organised,...,Organised,44,Medium,58,Press,37,Normal,Cover,Europe,NaN
1456,1456,10000,2014/9/19 0:00,54,Balanced,42.0,Normal,51,Mixed,Organised,...,Organised,44,Medium,58,Press,37,Normal,Cover,Europe,49.000000
1457,1457,10000,2015/9/10 0:00,54,Balanced,42.0,Normal,51,Mixed,Organised,...,Organised,44,Medium,58,Press,37,Normal,Cover,Europe,49.000000

In [5]:
# 实战训练——对球队明细teamattributes数据集实现行操作
df = pd.read_csv('../data/team_attributes.csv', index_col='id')
# df
# 分别利用标签索引|和位置索引|获得id=a1457的数据
df.loc[1457]
df.iloc[1457]
# ➢分别利用标签索引和位置索引获得id为a0、a2、a4的数据
df.loc[:5:2]
df.iloc[:5:2]
# 获得位置为双数的数据
df.loc[1::2]
# ➢获得buildUpPlaySpeed分数低于30的数据
df.loc[df.buildUpPlaySpeed < 30]
# 利用索引和切片获得前5行数据、位置为0、2、4数据
df.loc[:4:2]
# 删除行索引为a0的数据
df.drop(0)
# 删除行索引|为a0、a1的数据
df.drop([0, 1])

team_api_id                                10000
date                              2015/9/10 0:00
buildUpPlaySpeed                              54
buildUpPlaySpeedClass                   Balanced
buildUpPlayDribbling                        42.0
buildUpPlayDribblingClass                 Normal
buildUpPlayPassing                            51
buildUpPlayPassingClass                    Mixed
buildUpPlayPositioningClass            Organised
chanceCreationPassing                         47
chanceCreationPassingClass                Normal
chanceCreationCrossing                        52
chanceCreationCrossingClass               Normal
chanceCreationShooting                        32
chanceCreationShootingClass               Little
chanceCreationPositioningClass         Organised
defencePressure                               44
defencePressureClass                      Medium
defenceAggression                             58
defenceAggressionClass                     Press
defenceTeamWidth                              37
defenceTeamWidthClass                     Normal
defenceDefenderLineClass                   Cover
Name: 1457, dtype: object

team_api_id                                10000
date                              2015/9/10 0:00
buildUpPlaySpeed                              54
buildUpPlaySpeedClass                   Balanced
buildUpPlayDribbling                        42.0
buildUpPlayDribblingClass                 Normal
buildUpPlayPassing                            51
buildUpPlayPassingClass                    Mixed
buildUpPlayPositioningClass            Organised
chanceCreationPassing                         47
chanceCreationPassingClass                Normal
chanceCreationCrossing                        52
chanceCreationCrossingClass               Normal
chanceCreationShooting                        32
chanceCreationShootingClass               Little
chanceCreationPositioningClass         Organised
defencePressure                               44
defencePressureClass                      Medium
defenceAggression                             58
defenceAggressionClass                     Press
defenceTeamWidth                              37
defenceTeamWidthClass                     Normal
defenceDefenderLineClass                   Cover
Name: 1457, dtype: object

,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,buildUpPlayPositioningClass,chanceCreationPassing,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
id,,,,,,,,,,,,,,,,,,,,,
0,9930,2010/2/22 0:00,60,Balanced,NaN,Little,50,Mixed,Organised,60,...,55,Normal,Organised,50,Medium,55,Press,45,Normal,Cover
2,9930,2015/9/10 0:00,47,Balanced,41.0,Normal,54,Mixed,Organised,54,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
4,8485,2011/2/22 0:00,47,Balanced,NaN,Little,52,Mixed,Organised,53,...,52,Normal,Organised,47,Medium,47,Press,52,Normal,Cover

,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,buildUpPlayPositioningClass,chanceCreationPassing,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
id,,,,,,,,,,,,,,,,,,,,,
0,9930,2010/2/22 0:00,60,Balanced,NaN,Little,50,Mixed,Organised,60,...,55,Normal,Organised,50,Medium,55,Press,45,Normal,Cover
2,9930,2015/9/10 0:00,47,Balanced,41.0,Normal,54,Mixed,Organised,54,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
4,8485,2011/2/22 0:00,47,Balanced,NaN,Little,52,Mixed,Organised,53,...,52,Normal,Organised,47,Medium,47,Press,52,Normal,Cover

,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,buildUpPlayPositioningClass,chanceCreationPassing,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
id,,,,,,,,,,,,,,,,,,,,,
1,9930,2014/9/19 0:00,52,Balanced,48.0,Normal,56,Mixed,Organised,54,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
3,8485,2010/2/22 0:00,70,Fast,NaN,Little,70,Long,Organised,70,...,70,Lots,Organised,60,Medium,70,Double,70,Wide,Cover
5,8485,2012/2/22 0:00,58,Balanced,NaN,Little,62,Mixed,Organised,45,...,55,Normal,Organised,40,Medium,40,Press,60,Normal,Cover
7,8485,2014/9/19 0:00,58,Balanced,64.0,Normal,62,Mixed,Organised,56,...,57,Normal,Organised,41,Medium,42,Press,60,Normal,Cover
9,8576,2010/2/22 0:00,60,Balanced,NaN,Little,40,Mixed,Organised,45,...,55,Normal,Organised,30,Deep,70,Double,30,Narrow,Offside Trap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1449,8394,2015/9/10 0:00,52,Balanced,52.0,Normal,50,Mixed,Organised,52,...,57,Normal,Organised,48,Medium,43,Press,49,Normal,Cover
1451,8027,2015/9/10 0:00,54,Balanced,51.0,Normal,40,Mixed,Organised,46,...,52,Normal,Organised,44,Medium,47,Press,52,Normal,Cover
1453,10000,2011/2/22 0:00,52,Balanced,NaN,Little,52,Mixed,Organised,52,...,53,Normal,Organised,46,Medium,48,Press,53,Normal,Cover
1455,10000,2013/9/20 0:00,54,Balanced,NaN,Little,51,Mixed,Organised,47,...,32,Little,Organised,44,Medium,58,Press,37,Normal,Cover
1457,10000,2015/9/10 0:00,54,Balanced,42.0,Normal,51,Mixed,Organised,47,...,32,Little,Organised,44,Medium,58,Press,37,Normal,Cover

,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,buildUpPlayPositioningClass,chanceCreationPassing,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
id,,,,,,,,,,,,,,,,,,,,,
61,108893,2012/2/22 0:00,23,Slow,NaN,Little,33,Short,Organised,49,...,43,Normal,Organised,44,Medium,32,Contain,36,Normal,Cover
72,9825,2012/2/22 0:00,25,Slow,NaN,Little,32,Short,Organised,41,...,30,Little,Free Form,57,Medium,57,Press,52,Normal,Cover
120,8634,2012/2/22 0:00,24,Slow,NaN,Little,25,Short,Free Form,37,...,54,Normal,Free Form,66,Medium,63,Press,66,Normal,Cover
504,8305,2012/2/22 0:00,25,Slow,NaN,Little,40,Mixed,Organised,58,...,52,Normal,Organised,49,Medium,45,Press,47,Normal,Cover
505,8305,2013/9/20 0:00,29,Slow,NaN,Little,40,Mixed,Organised,58,...,52,Normal,Organised,49,Medium,45,Press,47,Normal,Cover
628,9885,2014/9/19 0:00,26,Slow,47.0,Normal,24,Short,Organised,64,...,72,Lots,Organised,23,Deep,67,Double,36,Normal,Cover
1035,8370,2015/9/10 0:00,29,Slow,52.0,Normal,44,Mixed,Organised,44,...,47,Normal,Organised,54,Medium,52,Press,63,Normal,Cover
1056,8560,2012/2/22 0:00,24,Slow,NaN,Little,36,Mixed,Organised,60,...,59,Normal,Organised,48,Medium,53,Press,70,Wide,Cover
1057,8560,2013/9/20 0:00,28,Slow,NaN,Little,36,Mixed,Organised,60,...,59,Normal,Organised,48,Medium,53,Press,70,Wide,Cover
1256,10003,2012/2/22 0:00,26,Slow,NaN,Little,24,Short,Organised,62,...,57,Normal,Free Form,48,Medium,58,Press,60,Normal,Cover
1294,8611,2012/2/22 0:00,25,Slow,NaN,Little,28,Short,Organised,44,...,37,Normal,Organised,62,Medium,68,Double,67,Wide,Cover
1309,10267,2012/2/22 0:00,20,Slow,NaN,Little,35,Mixed,Organised,38,...,55,Normal,Organised,51,Medium,38,Press,59,Normal,Cover
1310,10267,2013/9/20 0:00,20,Slow,NaN,Little,35,Mixed,Organised,38,...,55,Normal,Organised,51,Medium,38,Press,59,Normal,Cover
1337,10205,2012/2/22 0:00,20,Slow,NaN,Little,26,Short,Organised,43,...,58,Normal,Organised,51,Medium,51,Press,56,Normal,Cover
1338,10205,2013/9/20 0:00,24,Slow,NaN,Little,26,Short,Organised,43,...,58,Normal,Organised,51,Medium,51,Press,56,Normal,Cover
1410,10265,2012/2/22 0:00,25,Slow,NaN,Little,25,Short,Organised,32,...,50,Normal,Organised,60,Medium,58,Press,61,Normal,Cover

,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,buildUpPlayPositioningClass,chanceCreationPassing,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
id,,,,,,,,,,,,,,,,,,,,,
0,9930,2010/2/22 0:00,60,Balanced,NaN,Little,50,Mixed,Organised,60,...,55,Normal,Organised,50,Medium,55,Press,45,Normal,Cover
2,9930,2015/9/10 0:00,47,Balanced,41.0,Normal,54,Mixed,Organised,54,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
4,8485,2011/2/22 0:00,47,Balanced,NaN,Little,52,Mixed,Organised,53,...,52,Normal,Organised,47,Medium,47,Press,52,Normal,Cover

,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,buildUpPlayPositioningClass,chanceCreationPassing,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
id,,,,,,,,,,,,,,,,,,,,,
1,9930,2014/9/19 0:00,52,Balanced,48.0,Normal,56,Mixed,Organised,54,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
2,9930,2015/9/10 0:00,47,Balanced,41.0,Normal,54,Mixed,Organised,54,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
3,8485,2010/2/22 0:00,70,Fast,NaN,Little,70,Long,Organised,70,...,70,Lots,Organised,60,Medium,70,Double,70,Wide,Cover
4,8485,2011/2/22 0:00,47,Balanced,NaN,Little,52,Mixed,Organised,53,...,52,Normal,Organised,47,Medium,47,Press,52,Normal,Cover
5,8485,2012/2/22 0:00,58,Balanced,NaN,Little,62,Mixed,Organised,45,...,55,Normal,Organised,40,Medium,40,Press,60,Normal,Cover
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1453,10000,2011/2/22 0:00,52,Balanced,NaN,Little,52,Mixed,Organised,52,...,53,Normal,Organised,46,Medium,48,Press,53,Normal,Cover
1454,10000,2012/2/22 0:00,54,Balanced,NaN,Little,51,Mixed,Organised,47,...,50,Normal,Organised,44,Medium,55,Press,53,Normal,Cover
1455,10000,2013/9/20 0:00,54,Balanced,NaN,Little,51,Mixed,Organised,47,...,32,Little,Organised,44,Medium,58,Press,37,Normal,Cover
1456,10000,2014/9/19 0:00,54,Balanced,42.0,Normal,51,Mixed,Organised,47,...,32,Little,Organised,44,Medium,58,Press,37,Normal,Cover
1457,10000,2015/9/10 0:00,54,Balanced,42.0,Normal,51,Mixed,Organised,47,...,32,Little,Organised,44,Medium,58,Press,37,Normal,Cover

,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,buildUpPlayPositioningClass,chanceCreationPassing,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
id,,,,,,,,,,,,,,,,,,,,,
2,9930,2015/9/10 0:00,47,Balanced,41.0,Normal,54,Mixed,Organised,54,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
3,8485,2010/2/22 0:00,70,Fast,NaN,Little,70,Long,Organised,70,...,70,Lots,Organised,60,Medium,70,Double,70,Wide,Cover
4,8485,2011/2/22 0:00,47,Balanced,NaN,Little,52,Mixed,Organised,53,...,52,Normal,Organised,47,Medium,47,Press,52,Normal,Cover
5,8485,2012/2/22 0:00,58,Balanced,NaN,Little,62,Mixed,Organised,45,...,55,Normal,Organised,40,Medium,40,Press,60,Normal,Cover
6,8485,2013/9/20 0:00,62,Balanced,NaN,Little,45,Mixed,Organised,40,...,55,Normal,Organised,42,Medium,42,Press,60,Normal,Cover
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1453,10000,2011/2/22 0:00,52,Balanced,NaN,Little,52,Mixed,Organised,52,...,53,Normal,Organised,46,Medium,48,Press,53,Normal,Cover
1454,10000,2012/2/22 0:00,54,Balanced,NaN,Little,51,Mixed,Organised,47,...,50,Normal,Organised,44,Medium,55,Press,53,Normal,Cover
1455,10000,2013/9/20 0:00,54,Balanced,NaN,Little,51,Mixed,Organised,47,...,32,Little,Organised,44,Medium,58,Press,37,Normal,Cover
1456,10000,2014/9/19 0:00,54,Balanced,42.0,Normal,51,Mixed,Organised,47,...,32,Little,Organised,44,Medium,58,Press,37,Normal,Cover
1457,10000,2015/9/10 0:00,54,Balanced,42.0,Normal,51,Mixed,Organised,47,...,32,Little,Organised,44,Medium,58,Press,37,Normal,Cover

In [6]:
df = pd.read_csv('../data/team_attributes.csv', index_col='id')
# df
# ➢获得id=a3数据的buildUpPlaySpeed
#   ✓分别使用先获得行再获得列、先获得列再获得行的方式
df.loc[3, 'buildUpPlaySpeed']
df.buildUpPlaySpeed.loc[3]
# ➢获得a3、a5数据中的buildUpPlaySpeed和buildUpPlaySpeedClass
#   ✓分别使用先获得行再获得列、先获得列再获得行的方式
df.loc[[3, 5], ['buildUpPlaySpeed', 'buildUpPlaySpeedClass']]
df[['buildUpPlaySpeed', 'buildUpPlaySpeedClass']].loc[[3, 5]]
# ➢使用行列混合切片获得a3到a5数据的buildUpPlaySpeed和buildUpPlaySpeedClass
df.loc[3:5, 'buildUpPlaySpeed':'buildUpPlaySpeedClass']
# ➢修改所有数据中buildUpPlayDribbling为NAN的数据设置为0
df.loc[df['buildUpPlayDribbling'] == np.NAN] = 0
# ➢修改所有数据中buildUpPlaySpeed<30的数据buildUpPlaySpeed值为30
df.loc[df['buildUpPlaySpeed'] < 30] = 30

70

70

    buildUpPlaySpeed buildUpPlaySpeedClass
id
3                 70                  Fast
5                 58              Balanced

    buildUpPlaySpeed buildUpPlaySpeedClass
id
3                 70                  Fast
5                 58              Balanced

    buildUpPlaySpeed buildUpPlaySpeedClass
id
3                 70                  Fast
4                 47              Balanced
5                 58              Balanced

In [7]:
df = pd.read_csv('../data/team_attributes.csv')
# 实现buildUpPlaySpeed、buildUpPlayDribbling数据列的均值
df[['buildUpPlaySpeed', 'buildUpPlayDribbling']].mean()
# 统计显示buildUpPlaySpeed与buildUpPlayDribbling、buildUpPlayPassing的相关度
df[['buildUpPlaySpeed', 'buildUpPlayDribbling', 'buildUpPlayPassing']].corr()
# 列出buildUpPlaySpeed低于平均分的数据并按照从低到高排序
df[df['buildUpPlaySpeed'] < df['buildUpPlaySpeed'].mean()].sort_values('buildUpPlaySpeed')
# 统计buildUpPlaySpeedClass的唯一值数量(不重复元素的个数)与唯一值元素（不重复元素）
df['buildUpPlaySpeedClass'].nunique()
df['buildUpPlaySpeedClass'].unique()
# buildUpPlaySpeedClass 唯一值分布（计数）
df['buildUpPlaySpeedClass'].value_counts()

# buildUpPlaySpeedClass 为 Fast 的球队名称（需关联 team 表）
team = pd.read_csv('../data/team.csv')
fast_teams = df[df['buildUpPlaySpeedClass'] == 'Fast'].merge(team, on='team_api_id')
print(fast_teams[['team_long_name', 'team_short_name']])

buildUpPlaySpeed        52.462277
buildUpPlayDribbling    48.607362
dtype: float64

,buildUpPlaySpeed,buildUpPlayDribbling,buildUpPlayPassing
buildUpPlaySpeed,1.000000,0.067988,0.395506
buildUpPlayDribbling,0.067988,1.000000,-0.123613
buildUpPlayPassing,0.395506,-0.123613,1.000000

,id,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,buildUpPlayPositioningClass,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
1337,1337,10205,2012/2/22 0:00,20,Slow,NaN,Little,26,Short,Organised,...,58,Normal,Organised,51,Medium,51,Press,56,Normal,Cover
1310,1310,10267,2013/9/20 0:00,20,Slow,NaN,Little,35,Mixed,Organised,...,55,Normal,Organised,51,Medium,38,Press,59,Normal,Cover
1309,1309,10267,2012/2/22 0:00,20,Slow,NaN,Little,35,Mixed,Organised,...,55,Normal,Organised,51,Medium,38,Press,59,Normal,Cover
61,61,108893,2012/2/22 0:00,23,Slow,NaN,Little,33,Short,Organised,...,43,Normal,Organised,44,Medium,32,Contain,36,Normal,Cover
1338,1338,10205,2013/9/20 0:00,24,Slow,NaN,Little,26,Short,Organised,...,58,Normal,Organised,51,Medium,51,Press,56,Normal,Cover
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1449,1449,8394,2015/9/10 0:00,52,Balanced,52.0,Normal,50,Mixed,Organised,...,57,Normal,Organised,48,Medium,43,Press,49,Normal,Cover
664,664,8203,2015/9/10 0:00,52,Balanced,42.0,Normal,40,Mixed,Organised,...,50,Normal,Organised,42,Medium,51,Press,52,Normal,Cover
663,663,8203,2014/9/19 0:00,52,Balanced,42.0,Normal,40,Mixed,Organised,...,50,Normal,Organised,42,Medium,51,Press,52,Normal,Cover
933,933,8573,2015/9/10 0:00,52,Balanced,49.0,Normal,54,Mixed,Organised,...,53,Normal,Organised,42,Medium,47,Press,44,Normal,Cover
1453,1453,10000,2011/2/22 0:00,52,Balanced,NaN,Little,52,Mixed,Organised,...,53,Normal,Organised,46,Medium,48,Press,53,Normal,Cover

3

array(['Balanced', 'Fast', 'Slow'], dtype=object)

buildUpPlaySpeedClass
Balanced    1184
Fast         172
Slow         102
Name: count, dtype: int64

              team_long_name team_short_name
0                   Aberdeen             ABE
1                  FC Arouca             ARO
2                    Arsenal             ARS
3                Aston Villa             AVL
4                Aston Villa             AVL
..                       ...             ...
167                Willem II             WII
168             Wis?a Kraków             WIS
169            VfL Wolfsburg             WOL
170  Wolverhampton Wanderers             WOL
171  Wolverhampton Wanderers             WOL

[172 rows x 2 columns]